server {
    listen 127.0.0.1:8080;
    server_name localhost;
    
    # index index.html;

    # Tratamento de Erro Padrão
    error_page 404 /404.html;

    # Limite de Body (Testar erro 413) /post_body arquivos superiores a 100KB
    client_max_body_size 150000000; # 100 bytes apenas
    # 10000000

    # Rota Principal
    location / {
        root www/html;
        index index.html index.htm index.php;
        methods GET POST;
        autoindex off;
    }

    # Rota de Uploads (Permitir DELETE)
    location /upload {
        root www/uploads;
        methods GET POST DELETE;
        # autoindex on;       # Para testar listagem de diretório
        upload_store www/uploads;
    }

    # Rota Protegida (Testar permissão negada)
    location /protected {
        methods NONE;
    }

      location /directory {
        root www/uploads;
        autoindex on;
        methods GET;
    }

    # Rota de Redirecionamento
    location /redirect {
        redirect https://profile.intra.42.fr;
    }

    # Rota CGI
    location /cgi-bin {
        root ./www/cgi-bin;
        cgi .py /usr/bin/python3;       # Defina como seu servidor identifica CGI
        cgi .php /usr/bin/php-cgi;
        methods GET POST;
    }
    
    
    location /post_body {
        methods POST;
        upload_store www/uploads;
    }
}

server {
    listen 172.31.194.108:8080;
    server_name interface2;
    
    # index index.html;

    # Tratamento de Erro Padrão
    error_page 404 /404.html;

    # Limite de Body (Testar erro 413) /post_body arquivos superiores a 100KB
    client_max_body_size 100; # 100 bytes apenas

    # Rota Principal
    location / {
        root www/html3;
        index index.html index.htm index.php;
        methods GET POST;
        autoindex off;
    }
}