server {
  listen 192.168.1.255:8080;

  server_name my_server;

  error_page 404 /errors/404.html;

  client_max_body_size 10000000;

  location / {
    root /var/www/html;
    index index.html index.htm;
    methods GET HEAD;
  }

  location /upload {
    methods POST;
    upload_store /tmp/uploads;
  }
  
  location /php {
    cgi .php /usr/bin/php-cgi;
  }
}