server {
    listen localhost:8080;
    # root /var/www;  # default

    # 1) Root: only GET
    location / {
        methods GET;
        root www/html;     # seu root para /
        index index.html;
    }

    # 2) PUT store
    location /put_test/ {
        methods POST;
        upload_store /tmp/;   # pasta onde o servidor deve gravar arquivos
    }

    # 3) .bla -> cgi_test
    location /cgi-bin {
        root www/cgi-bin;
        cgi .bla /home/yufonten/WebServer/www/cgi-bin/ubuntu_cgi_tester;     # caminho absoluto para o cgi_test fornecido pelo tester
    }

    client_max_body_size 100;      # bytes
    # 4) /post_body: accept POST with max body 100
    location /post_body {
        methods POST;
        # comportamento: você decide se grava em disco ou só responde com corpo recebido
        upload_store /tmp;
    }

    # 5) /directory/ -> YoupiBanane root + default index youpi.bad_extension
    location /directory {
        methods GET;
        root www/YoupiBanane;
        # default searching filename:
        index youpi.bad_extension;
        # alternatively, implement explicit lookup for youpi.bad_extension if path ends with /
    }

    # 6) Global cgi -> Deve aceitar qualquer caminho que termine em um arquivo do tipo da extensõ descrita
    location ~/.bla$ {
        root www/cgi-bin;
        cgi .bla www/cgi-bin/ubuntu_cgi_tester;
    }
}